; Development overrides
error_reporting=E_ALL
display_errors=1
log_errors=1
zend.assertions=1
xdebug.mode=debug,develop,coverage
xdebug.start_with_request=trigger
xdebug.discover_client_host=1
xdebug.client_port=9003
